# Sane power behaviour for old laptops.
[Login]
HandlePowerKey=poweroff
HandleLidSwitch=suspend
HandleLidSwitchExternalPower=suspend
HandleLidSwitchDocked=ignore
IdleAction=ignore
KillUserProcesses=no
# small RAM: don't keep logind's runtime dir huge
RuntimeDirectorySize=10%
